version: '3'
services:
  backend:
    build: .
    ports:
      - "5050:5050"
    env_file:
      - .env
    networks:
      - backend_network
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  test:
    build: .
    command: npm test
    env_file:
      - .env.test
    networks:
      - backend_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=test

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend_network
    volumes:
      - ./redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--dir", "/data"]

networks:
  backend_network:
    driver: bridge