version: '3'
services:
  backend:
    build: .
    ports:
      - "5050:5050"
    env_file:
      - .env
    networks:
      - backend_network
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge