version: '3'
services:
  backend:
    build: .
    ports:
      - "5050:5050"
    env_file:
      - .env
    networks:
      - backend_network
    # Wait-for-host workaround (optional, depending on timing)
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  backend_network:
    driver: bridge